apiVersion: apps/v1
kind: Deployment
metadata:
  name: lk-controller
spec:
  replicas: 2
  selector:
    matchLabels: { app: lk-controller }
  template:
    metadata:
      labels: { app: lk-controller }
    spec:
      containers:
      - name: controller
        image: ghcr.io/yourorg/lk-controller:latest
        ports: [{ containerPort: 8080 }]
        env:
        - name: LIVEKIT_URL
          valueFrom: { secretKeyRef: { name: livekit-secrets, key: LIVEKIT_URL } }
        - name: LIVEKIT_API_KEY
          valueFrom: { secretKeyRef: { name: livekit-secrets, key: LIVEKIT_API_KEY } }
        - name: LIVEKIT_API_SECRET
          valueFrom: { secretKeyRef: { name: livekit-secrets, key: LIVEKIT_API_SECRET } }
        - name: CONTROLLER_TOKEN_TTL_SECONDS
          value: "900"
---
apiVersion: v1
kind: Service
metadata:
  name: lk-controller
spec:
  selector: { app: lk-controller }
  ports:
  - port: 80
    targetPort: 8080
